using GeoMineralTrace.Core.Rockhounding;
using GeoMineralTrace.Rockhounding.Storage;

namespace GeoMineralTrace.Rockhounding.Glossary;

/// <summary>
/// Offline priority mineral/gem catalog (~55 species). Structured public-domain facts only;
/// descriptions are generated via <see cref="MineralDescriptionBuilder"/> (no Mindat prose).
/// </summary>
public static class PriorityGlossarySeed
{
    public static IReadOnlyList<MineralSpecies> All { get; } = BuildAll();

    private static IReadOnlyList<MineralSpecies> BuildAll() =>
    [
        // NER priority set
        BuildSpecies("Obsidian", ["volcanic glass"], null, "Amorphous", 5, 5.5,
            "Black, dark brown, mahogany", "Vitreous", "Rock / volcanic glass"),
        BuildSpecies("Garnet", ["garnet group"], "X₃Y₂(SiO₄)₃", "Isometric", 6.5, 7.5,
            "Red, orange, green, brown, black", "Vitreous to resinous", "Mineral group", null, "Q105374"),
        BuildSpecies("Almandine", ["almandite"], "Fe₃Al₂(SiO₄)₃", "Isometric", 7, 7.5,
            "Deep red to reddish brown", "Vitreous", "IMA approved", null, "Q407258"),
        BuildSpecies("Diamond", [], "C", "Isometric", 10, 10,
            "Colorless, yellow, brown, rarely fancy colors", "Adamantine", "IMA approved", null, "Q5283"),
        BuildSpecies("Turquoise", [], "CuAl₆(PO₄)₄(OH)₈·4H₂O", "Triclinic", 5, 6,
            "Blue to green", "Waxy to subvitreous", "IMA approved", null, "Q178325"),
        BuildSpecies("Opal", [], "SiO₂·nH₂O", "Amorphous", 5.5, 6.5,
            "Colorless to white; play-of-color varieties", "Vitreous to resinous", "IMA approved", null, "Q179900"),
        BuildSpecies("Agate", ["banded chalcedony"], "SiO₂", "Trigonal (cryptocrystalline)", 6.5, 7,
            "Banded multicolor", "Waxy to vitreous", "Gem variety", null, "Q17103"),
        BuildSpecies("Jasper", [], "SiO₂", "Trigonal (cryptocrystalline)", 6.5, 7,
            "Red, brown, yellow, green (opaque)", "Vitreous to dull", "Gem variety"),
        BuildSpecies("Amethyst", [], "SiO₂", "Trigonal", 7, 7,
            "Purple to violet", "Vitreous", "Gem variety"),
        BuildSpecies("Quartz", ["rock crystal"], "SiO₂", "Trigonal", 7, 7,
            "Colorless, white, and many colored varieties", "Vitreous", "IMA approved", null, "Q43010"),
        BuildSpecies("Fluorite", ["fluorspar"], "CaF₂", "Isometric", 4, 4,
            "Purple, green, blue, yellow, colorless", "Vitreous", "IMA approved", null, "Q182299"),
        BuildSpecies("Beryl", [], "Be₃Al₂Si₆O₁₈", "Hexagonal", 7.5, 8,
            "Colorless, green, blue, yellow, pink", "Vitreous", "IMA approved"),
        BuildSpecies("Aquamarine", [], "Be₃Al₂Si₆O₁₈", "Hexagonal", 7.5, 8,
            "Pale blue to blue-green", "Vitreous", "Gem variety"),
        BuildSpecies("Emerald", [], "Be₃Al₂Si₆O₁₈", "Hexagonal", 7.5, 8,
            "Green", "Vitreous", "Gem variety"),
        BuildSpecies("Topaz", [], "Al₂SiO₄(F,OH)₂", "Orthorhombic", 8, 8,
            "Colorless, yellow, blue, pink, brown", "Vitreous", "IMA approved"),
        BuildSpecies("Tourmaline", ["tourmaline group"], "Complex borosilicate", "Trigonal", 7, 7.5,
            "Black, pink, green, blue, multicolor", "Vitreous", "Mineral group"),
        BuildSpecies("Peridot", ["olivine", "chrysolite"], "(Mg,Fe)₂SiO₄", "Orthorhombic", 6.5, 7,
            "Olive to yellow-green", "Vitreous", "Gem variety"),
        BuildSpecies("Jade", ["nephrite", "jadeite"], "Ca₂(Mg,Fe)₅Si₈O₂₂(OH)₂ / NaAlSi₂O₆",
            "Monoclinic (nephrite/jadeite)", 6, 7,
            "Green, white, lavender, black", "Greasy to vitreous",
            "Gem variety (nephrite or jadeite)"),
        BuildSpecies("Malachite", [], "Cu₂CO₃(OH)₂", "Monoclinic", 3.5, 4,
            "Bright green, banded", "Silky to vitreous", "IMA approved"),
        BuildSpecies("Azurite", [], "Cu₃(CO₃)₂(OH)₂", "Monoclinic", 3.5, 4,
            "Deep blue", "Vitreous to dull", "IMA approved"),
        BuildSpecies("Pyrite", ["fool's gold"], "FeS₂", "Isometric", 6, 6.5,
            "Pale brass-yellow", "Metallic", "IMA approved", null, "Q102523"),
        BuildSpecies("Gold", ["native gold"], "Au", "Isometric", 2.5, 3,
            "Yellow", "Metallic", "IMA approved", null, "Q897"),
        BuildSpecies("Copper", ["native copper"], "Cu", "Isometric", 2.5, 3,
            "Copper-red, tarnishes brown/green", "Metallic", "IMA approved", null, "Q753"),
        BuildSpecies("Silver", ["native silver"], "Ag", "Isometric", 2.5, 3,
            "Silver-white, tarnishes black", "Metallic", "IMA approved", null, "Q1090"),
        BuildSpecies("Sunstone", ["heliolite"], "(Ca,Na)(Al,Si)₄O₈", "Triclinic", 6, 6.5,
            "Orange to red with aventurescence", "Vitreous", "Gem variety"),
        BuildSpecies("Labradorite", [], "(Ca,Na)(Al,Si)₄O₈", "Triclinic", 6, 6.5,
            "Gray with labradorescence (blue/green flash)", "Vitreous", "IMA approved", null, "Q409691"),
        BuildSpecies("Moonstone", [], "KAlSi₃O₈", "Monoclinic", 6, 6.5,
            "White to peach with adularescence", "Vitreous", "Gem variety"),

        // Common gems / minerals
        BuildSpecies("Calcite", [], "CaCO₃", "Trigonal", 3, 3,
            "Colorless, white, and many colors", "Vitreous to pearly", "IMA approved"),
        BuildSpecies("Gypsum", ["selenite", "alabaster"], "CaSO₄·2H₂O", "Monoclinic", 1.5, 2,
            "Colorless, white, gray, yellowish", "Vitreous to pearly", "IMA approved"),
        BuildSpecies("Hematite", [], "Fe₂O₃", "Trigonal", 5, 6,
            "Steel-gray to red", "Metallic to earthy", "IMA approved"),
        BuildSpecies("Chalcedony", [], "SiO₂", "Trigonal (cryptocrystalline)", 6.5, 7,
            "White, gray, blue, brown", "Waxy", "Gem variety"),
        BuildSpecies("Corundum", [], "Al₂O₃", "Trigonal", 9, 9,
            "Colorless to any color", "Adamantine to vitreous", "IMA approved"),
        BuildSpecies("Ruby", [], "Al₂O₃", "Trigonal", 9, 9,
            "Red", "Adamantine to vitreous", "Gem variety"),
        BuildSpecies("Sapphire", [], "Al₂O₃", "Trigonal", 9, 9,
            "Blue and other non-red colors", "Adamantine to vitreous", "Gem variety"),
        BuildSpecies("Citrine", [], "SiO₂", "Trigonal", 7, 7,
            "Yellow to orange-brown", "Vitreous", "Gem variety"),
        BuildSpecies("Rose Quartz", [], "SiO₂", "Trigonal", 7, 7,
            "Pink", "Vitreous", "Gem variety"),
        BuildSpecies("Smoky Quartz", ["cairngorm"], "SiO₂", "Trigonal", 7, 7,
            "Brown to gray-black", "Vitreous", "Gem variety"),
        BuildSpecies("Chrysocolla", [], "Cu₂₋ₓAlₓ(H₂₋ₓSi₂O₅)(OH)₄·nH₂O", "Orthorhombic", 2, 4,
            "Blue to green", "Vitreous to earthy", "IMA approved", null, "Q407218"),
        BuildSpecies("Feldspar", ["feldspar group"], "(K,Na,Ca)(Al,Si)₄O₈", "Triclinic / monoclinic", 6, 6.5,
            "White, pink, gray, green", "Vitreous", "Mineral group", null, "Q180802"),
        BuildSpecies("Magnetite", [], "Fe₃O₄", "Isometric", 5.5, 6.5,
            "Black", "Metallic", "IMA approved"),
        BuildSpecies("Galena", [], "PbS", "Isometric", 2.5, 2.5,
            "Lead-gray", "Metallic", "IMA approved"),
        BuildSpecies("Sphalerite", ["zinc blende"], "ZnS", "Isometric", 3.5, 4,
            "Yellow, brown, black, red", "Resinous to adamantine", "IMA approved"),
        BuildSpecies("Barite", ["baryte"], "BaSO₄", "Orthorhombic", 3, 3.5,
            "Colorless, white, blue, yellow", "Vitreous", "IMA approved"),
        BuildSpecies("Celestine", ["celestite"], "SrSO₄", "Orthorhombic", 3, 3.5,
            "Colorless, pale blue, white", "Vitreous", "IMA approved"),
        BuildSpecies("Apatite", ["apatite group"], "Ca₅(PO₄)₃(F,Cl,OH)", "Hexagonal", 5, 5,
            "Green, blue, yellow, violet, colorless", "Vitreous", "Mineral group"),
        BuildSpecies("Epidote", [], "Ca₂(Al,Fe)₃(SiO₄)₃(OH)", "Monoclinic", 6, 7,
            "Pistachio to dark green", "Vitreous", "IMA approved"),
        BuildSpecies("Actinolite", [], "Ca₂(Mg,Fe)₅Si₈O₂₂(OH)₂", "Monoclinic", 5, 6,
            "Green to gray-green", "Vitreous to silky", "IMA approved"),
        BuildSpecies("Nephrite", ["nephrite jade"], "Ca₂(Mg,Fe)₅Si₈O₂₂(OH)₂", "Monoclinic", 6, 6.5,
            "Cream to dark green", "Greasy to vitreous", "Rock / gem variety"),
        BuildSpecies("Jadeite", ["jadeite jade"], "NaAlSi₂O₆", "Monoclinic", 6.5, 7,
            "Green, white, lavender", "Vitreous to greasy", "IMA approved"),
        BuildSpecies("Carnelian", [], "SiO₂", "Trigonal (cryptocrystalline)", 6.5, 7,
            "Orange to red-brown", "Waxy", "Gem variety"),
        BuildSpecies("Onyx", [], "SiO₂", "Trigonal (cryptocrystalline)", 6.5, 7,
            "Black and white bands", "Waxy", "Gem variety"),
        BuildSpecies("Lapis Lazuli", ["lapis"], "Na₇Ca(Al₆Si₆O₂₄)(SO₄)(S₃)·H₂O (lazurite rock)",
            "Isometric (lazurite)", 5, 5.5,
            "Deep blue with pyrite flecks", "Dull to vitreous", "Rock / gem rock"),
        BuildSpecies("Sodalite", [], "Na₈(Al₆Si₆O₂₄)Cl₂", "Isometric", 5.5, 6,
            "Blue, white, gray", "Vitreous to greasy", "IMA approved"),
        BuildSpecies("Kunzite", ["spodumene variety"], "LiAlSi₂O₆", "Monoclinic", 6.5, 7,
            "Pink to lilac", "Vitreous", "Gem variety"),
        BuildSpecies("Zircon", [], "ZrSiO₄", "Tetragonal", 6.5, 7.5,
            "Colorless, brown, red, blue, green", "Adamantine to vitreous", "IMA approved"),
        BuildSpecies("Spinel", [], "MgAl₂O₄", "Isometric", 7.5, 8,
            "Red, pink, blue, black, colorless", "Vitreous", "IMA approved"),
        BuildSpecies("Garnet (Pyrope)", ["pyrope"], "Mg₃Al₂(SiO₄)₃", "Isometric", 7, 7.5,
            "Blood-red to purplish red", "Vitreous", "IMA approved"),
        BuildSpecies("Thunder Egg", ["thunderegg"], "SiO₂ (agate/chalcedony fill)", "Amorphous / cryptocrystalline",
            6.5, 7, "Multicolor agate core in rhyolite", "Waxy to vitreous", "Rock / volcanic nodule"),
        BuildSpecies("Petrified Wood", ["fossil wood"], "SiO₂ (replacement)", "Trigonal (cryptocrystalline)", 6.5, 7,
            "Earth tones preserving wood grain", "Vitreous to waxy", "Rock / fossil replacement"),
        BuildSpecies("Geode", [], "SiO₂ / carbonate lined cavity", "Variable", 3, 7,
            "Crystal-lined hollow nodule", "Vitreous", "Rock / geological feature"),
    ];

    public static MineralSpecies BuildSpecies(
        string name,
        IReadOnlyList<string>? aliases = null,
        string? formula = null,
        string? crystalSystem = null,
        double? mohsMin = null,
        double? mohsMax = null,
        string? colorRange = null,
        string? luster = null,
        string? imaStatus = null,
        int? imaYear = null,
        string? wikidataId = null)
    {
        var id = MineralGlossaryStore.Slugify(name);
        var description = MineralDescriptionBuilder.Build(
            name, formula, crystalSystem, mohsMin, mohsMax, colorRange, luster, imaStatus, imaYear);

        return new MineralSpecies
        {
            Id = id,
            Name = name,
            Aliases = aliases ?? [],
            Formula = formula,
            CrystalSystem = crystalSystem,
            MohsMin = mohsMin,
            MohsMax = mohsMax,
            ColorRange = colorRange,
            Luster = luster,
            ImaStatus = imaStatus,
            ImaYear = imaYear,
            Description = description,
            WikidataId = wikidataId,
            UpdatedUtc = DateTimeOffset.UtcNow,
            ImageCount = 0
        };
    }
}
